const fs = require('fs');
const path = require('path');

const ROOT = process.cwd();
const basePath = path.join(ROOT, 'src/data/base_codes.json');
const routesPath = path.join(ROOT, 'src/data/valid_routes.json');
const messagesDir = path.join(ROOT, 'messages');

const symptomTokens = {
  en: {
    symp_abs_warning: 'ABS / traction control warning light is on',
    symp_airbag_warning: 'Airbag or SRS warning light is on',
    symp_module_warning: 'Multiple warning lights or module communication warnings',
  },
  tr: {
    symp_abs_warning: 'ABS / çekiş kontrol uyarı lambası yanıyor',
    symp_airbag_warning: 'Airbag veya SRS uyarı lambası yanıyor',
    symp_module_warning: 'Birden fazla uyarı lambası veya modül iletişim uyarısı var',
  },
  de: {
    symp_abs_warning: 'ABS- oder Traktionskontrollleuchte ist an',
    symp_airbag_warning: 'Airbag- oder SRS-Warnleuchte ist an',
    symp_module_warning: 'Mehrere Warnleuchten oder Modul-Kommunikationswarnungen',
  },
  es: {
    symp_abs_warning: 'Luz de ABS o control de tracción encendida',
    symp_airbag_warning: 'Luz de airbag o SRS encendida',
    symp_module_warning: 'Varias luces de advertencia o avisos de comunicación de módulos',
  },
  fr: {
    symp_abs_warning: 'Voyant ABS ou antipatinage allumé',
    symp_airbag_warning: 'Voyant airbag ou SRS allumé',
    symp_module_warning: 'Plusieurs voyants ou alertes de communication entre modules',
  },
};

const systemProfiles = {
  chassis: {
    symptoms: ['symp_abs_warning', 'symp_speedometer_erratic', 'symp_cruise_not_working', 'symp_vibration', 'symp_reduced_power_mode'],
    causes: ['cause_wiring_damage', 'cause_connector_corrosion', 'cause_vss', 'cause_brake_switch', 'cause_power_steering_sensor'],
    difficulty: 'diff_moderate',
    cost: '$80 - $1200',
    label: 'ABS/chassis',
    source: 'Reviewed against public generic OBD-II C/chassis code listings and ABS/chassis diagnostic terminology.',
  },
  body: {
    symptoms: ['symp_airbag_warning', 'symp_module_warning', 'symp_battery_drain', 'symp_no_start', 'symp_cruise_not_working'],
    causes: ['cause_wiring_damage', 'cause_connector_corrosion', 'cause_battery', 'cause_pcm_failure', 'cause_pcm_software'],
    difficulty: 'diff_professional',
    cost: '$100 - $1500',
    label: 'body/SRS',
    source: 'Reviewed against public generic OBD-II B/body examples and SRS/body diagnostic terminology.',
  },
  network: {
    symptoms: ['symp_module_warning', 'symp_check_engine', 'symp_no_start', 'symp_reduced_power_mode', 'symp_battery_drain'],
    causes: ['cause_wiring_damage', 'cause_connector_corrosion', 'cause_battery', 'cause_alternator', 'cause_pcm_failure'],
    difficulty: 'diff_professional',
    cost: '$120 - $2000',
    label: 'CAN/module communication',
    source: 'Reviewed against public generic OBD-II U/network code listings and CAN/module communication terminology.',
  },
};

const verifiedRows = [
  ['C0000', 'chassis', 'Vehicle Speed Information Circuit Malfunction'],
  ['C0035', 'chassis', 'Left Front Wheel Speed Sensor Circuit'],
  ['C0040', 'chassis', 'Right Front Wheel Speed Sensor Circuit'],
  ['C0041', 'chassis', 'Brake Pedal Switch Circuit'],
  ['C0045', 'chassis', 'Left Rear Wheel Speed Sensor Circuit'],
  ['C0046', 'chassis', 'Brake Pressure Sensor A/B'],
  ['C0050', 'chassis', 'Right Rear Wheel Speed Sensor Circuit'],
  ['C0051', 'chassis', 'Steering Wheel Position Sensor'],
  ['C0060', 'chassis', 'Left Front ABS Solenoid 1 Circuit'],
  ['C0065', 'chassis', 'Left Front ABS Solenoid 2 Circuit'],
  ['C0070', 'chassis', 'Right Front ABS Solenoid 1 Circuit'],
  ['C0075', 'chassis', 'Right Front ABS Solenoid 2 Circuit'],
  ['C0080', 'chassis', 'Left Rear ABS Solenoid 1 Circuit'],
  ['C0085', 'chassis', 'Left Rear ABS Solenoid 2 Circuit'],
  ['C0090', 'chassis', 'Right Rear ABS Solenoid 1 Circuit'],
  ['C0095', 'chassis', 'Right Rear ABS Solenoid 2 Circuit'],
  ['C0110', 'chassis', 'Pump Motor Circuit'],
  ['C0121', 'chassis', 'Valve Relay Circuit'],
  ['C0128', 'chassis', 'Low Brake Fluid Circuit'],
  ['C0141', 'chassis', 'Left TCS Solenoid 1 Circuit'],
  ['C0146', 'chassis', 'Left TCS Solenoid 2 Circuit'],
  ['C0151', 'chassis', 'Right TCS Solenoid 1 Circuit'],
  ['C0156', 'chassis', 'Right TCS Solenoid 2 Circuit'],
  ['C0161', 'chassis', 'ABS / TCS Brake Switch Circuit'],
  ['C0221', 'chassis', 'Right Front Wheel Speed Sensor Circuit Open'],
  ['C0222', 'chassis', 'Right Front Wheel Speed Signal Missing'],
  ['C0223', 'chassis', 'Right Front Wheel Speed Signal Erratic'],
  ['C0225', 'chassis', 'Left Front Wheel Speed Sensor Circuit Open'],
  ['C0226', 'chassis', 'Left Front Wheel Speed Signal Missing'],
  ['C0227', 'chassis', 'Left Front Wheel Speed Signal Erratic'],
  ['C0229', 'chassis', 'Drop Out of Front Wheel Speed Signals'],
  ['C0235', 'chassis', 'Rear Wheel Speed Signal Circuit Open'],
  ['C0236', 'chassis', 'Rear Wheel Speed Signal Missing'],
  ['C0237', 'chassis', 'Rear Wheel Speed Signal Erratic'],
  ['C0238', 'chassis', 'Wheel Speed Mismatch'],
  ['C0241', 'chassis', 'EBCM Control Valve Circuit Fault'],
  ['C0245', 'chassis', 'Wheel Speed Sensor Frequency Error'],
  ['C0254', 'chassis', 'EBCM Control Valve Solenoid Circuit'],
  ['C0265', 'chassis', 'EBCM Motor Relay Circuit'],
  ['C0266', 'chassis', 'EBCM Relay Circuit Low'],
  ['C0267', 'chassis', 'EBCM Relay Circuit High'],
  ['C0268', 'chassis', 'Pump Motor Circuit Shorted'],
  ['C0269', 'chassis', 'Excessive Dump / Isolation Time Front Axle'],
  ['C0271', 'chassis', 'EBCM Malfunction'],
  ['C0272', 'chassis', 'EBCM Main Relay Circuit'],
  ['C0273', 'chassis', 'EBCM Control Valve Relay Circuit'],
  ['C0274', 'chassis', 'Excessive Dump / Isolation Time Rear Axle'],
  ['C0279', 'chassis', 'Powertrain Configuration Not Valid'],
  ['C0281', 'chassis', 'Brake Switch Circuit'],
  ['C0283', 'chassis', 'Traction Switch Shorted to Ground'],
  ['C0284', 'chassis', 'Traction Switch Shorted to Battery'],
  ['C0286', 'chassis', 'ABS Indicator Lamp Circuit'],
  ['C0287', 'chassis', 'Delivered Torque Signal Circuit'],
  ['C0288', 'chassis', 'Brake Warning Lamp Circuit'],
  ['C0290', 'chassis', 'Lost Communication With PCM'],
  ['C0291', 'chassis', 'Lost Communication With BCM'],
  ['C0292', 'chassis', 'VSES Combination Sensor Circuit'],
  ['C0297', 'chassis', 'Powertrain Configuration Data Not Received'],
  ['C0298', 'chassis', 'Powertrain Configuration Data Invalid'],
  ['C0300', 'chassis', 'Rear Speed Sensor Circuit'],
  ['C0305', 'chassis', 'Front Speed Sensor Circuit'],
  ['C0306', 'chassis', 'Motor A/B Circuit'],
  ['C0308', 'chassis', 'Motor A/B Circuit Low'],
  ['C0309', 'chassis', 'Motor A/B Circuit High'],
  ['C0310', 'chassis', 'Motor A/B Circuit Open'],
  ['C0315', 'chassis', 'Motor Ground Circuit Open'],
  ['C0321', 'chassis', 'Transfer Case Lock Circuit'],
  ['C0323', 'chassis', 'T-Case Lock Circuit Low'],
  ['C0324', 'chassis', 'T-Case Lock Circuit High'],
  ['C0327', 'chassis', 'Encoder Circuit Malfunction'],
  ['C0357', 'chassis', 'Park Switch Circuit High'],
  ['C0359', 'chassis', 'Four Wheel Drive Low Range Circuit'],
  ['C0362', 'chassis', '4WD High Circuit'],
  ['C0367', 'chassis', 'Front Axle Control Circuit High'],
  ['C0374', 'chassis', 'General System Malfunction'],
  ['C0376', 'chassis', 'Front / Rear Shaft Speed Mismatch'],
  ['C0379', 'chassis', 'Front Axle System Malfunction'],
  ['C0387', 'chassis', 'Unable to Complete Shift'],
  ['C0472', 'chassis', 'Steering Handwheel Speed Sensor Signal V Low'],
  ['C0473', 'chassis', 'Steering Handwheel Speed Sensor Signal V High'],
  ['C0495', 'chassis', 'EVO Actuator Circuit'],
  ['C0498', 'chassis', 'EVO Actuator Circuit Low'],
  ['C0499', 'chassis', 'EVO Actuator Circuit High'],
  ['C0503', 'chassis', 'Steering Assist Control Solenoid Return Circuit'],
  ['C0504', 'chassis', 'Steering Assist Control Solenoid Circuit'],
  ['C0550', 'chassis', 'ECU Malfunction'],
  ['C0559', 'chassis', 'EEPROM Checksum Error'],
  ['C0563', 'chassis', 'Calibration ROM Checksum Error'],
  ['C0577', 'chassis', 'Left Front Solenoid Circuit Low'],
  ['C0578', 'chassis', 'Left Front Solenoid Circuit High'],
  ['C0579', 'chassis', 'Left Front Solenoid Circuit Open'],
  ['C0582', 'chassis', 'Right Front Solenoid Circuit Low'],
  ['C0583', 'chassis', 'Right Front Solenoid Circuit High'],
  ['C0584', 'chassis', 'Right Front Solenoid Circuit Open'],
  ['C0587', 'chassis', 'Left Rear Solenoid Circuit Low'],
  ['C0588', 'chassis', 'Left Rear Solenoid Circuit High'],
  ['C0589', 'chassis', 'Left Rear Solenoid Circuit Open'],
  ['C0592', 'chassis', 'Right Rear Solenoid Circuit Low'],
  ['C0593', 'chassis', 'Right Rear Solenoid Circuit High'],
  ['C0594', 'chassis', 'Right Rear Solenoid Circuit Open'],
  ['C0611', 'chassis', 'VIN Information Error'],
  ['C0615', 'chassis', 'Left Front Position Sensor Circuit'],
  ['C0620', 'chassis', 'Right Front Position Sensor Circuit'],
  ['C0625', 'chassis', 'Left Rear Position Sensor Circuit'],
  ['C0628', 'chassis', 'Level Control Position Sensor Circuit High'],
  ['C0630', 'chassis', 'Right Rear Position Sensor Circuit'],
  ['C0635', 'chassis', 'Left Rear Normal Force Circuit'],
  ['C0638', 'chassis', 'Left Rear Normal Force Circuit High'],
  ['C0640', 'chassis', 'Right Front Normal Force Circuit'],
  ['C0643', 'chassis', 'Right Front Normal Force Circuit High'],
  ['C0655', 'chassis', 'Level Control Compressor Relay Malfunction'],
  ['C0657', 'chassis', 'Level Control Compressor Circuit Low'],
  ['C0658', 'chassis', 'Level Control Compressor Circuit High'],
  ['C0660', 'chassis', 'Level Control Exhaust Valve Circuit'],
  ['C0662', 'chassis', 'Level Control Exhaust Valve Circuit Low'],
  ['C0663', 'chassis', 'Level Control Exhaust Valve Circuit High'],
  ['C0665', 'chassis', 'Chassis Pitch Signal Circuit'],
  ['C0690', 'chassis', 'Damper Control Relay Circuit'],
  ['C0691', 'chassis', 'Damper Control Relay Circuit Range / Performance'],
  ['C0693', 'chassis', 'Damper Control Relay Circuit High'],
  ['C0695', 'chassis', 'Left Position Sensor Overcurrent'],
  ['C0696', 'chassis', 'Right Position Sensor Overcurrent'],
  ['C0710', 'chassis', 'Steering Position Signal Malfunction'],
  ['C0750', 'chassis', 'Left Front Tire Pressure Sensor Circuit'],
  ['C0755', 'chassis', 'Right Front Tire Pressure Sensor Circuit'],
  ['C0760', 'chassis', 'Left Rear Tire Pressure Sensor Circuit'],
  ['C0765', 'chassis', 'Right Rear Tire Pressure Sensor Circuit'],
  ['C0800', 'chassis', 'Device Power 1 Circuit Malfunction'],
  ['C0896', 'chassis', 'Device Voltage Malfunction'],

  ['B0023', 'body', 'Driver Side Airbag Deployment Loop'],
  ['B0026', 'body', 'Passenger Side Airbag Deployment Loop'],
  ['B0033', 'body', 'Second Row Left Frontal Deployment Loop'],
  ['B0040', 'body', 'Third Row Left Frontal Deployment Loop'],
  ['B0042', 'body', 'Third Row Left Side Airbag Deployment Loop'],
  ['B0044', 'body', 'Third Row Right Side Airbag Deployment Loop'],
  ['B0092', 'body', 'Passenger Presence Detection Performance'],

  ['U0001', 'network', 'High Speed CAN Communication Bus'],
  ['U0002', 'network', 'High Speed CAN Communication Bus Performance'],
  ['U0003', 'network', 'High Speed CAN Communication Bus (+) Open'],
  ['U0004', 'network', 'High Speed CAN Communication Bus (+) Low'],
  ['U0005', 'network', 'High Speed CAN Communication Bus (+) High'],
  ['U0006', 'network', 'High Speed CAN Communication Bus (-) Open'],
  ['U0007', 'network', 'High Speed CAN Communication Bus (-) Low'],
  ['U0008', 'network', 'High Speed CAN Communication Bus (-) High'],
  ['U0009', 'network', 'High Speed CAN Communication Bus (-) Shorted to Bus (+)'],
  ['U0010', 'network', 'Medium Speed CAN Communication Bus'],
  ['U0011', 'network', 'Medium Speed CAN Communication Bus Performance'],
  ['U0012', 'network', 'Medium Speed CAN Communication Bus (+) Open'],
  ['U0013', 'network', 'Medium Speed CAN Communication Bus (+) Low'],
  ['U0014', 'network', 'Medium Speed CAN Communication Bus (+) High'],
  ['U0015', 'network', 'Medium Speed CAN Communication Bus (-) Open'],
  ['U0016', 'network', 'Medium Speed CAN Communication Bus (-) Low'],
  ['U0017', 'network', 'Medium Speed CAN Communication Bus (-) High'],
  ['U0018', 'network', 'Medium Speed CAN Communication Bus (-) Shorted to Bus (+)'],
  ['U0019', 'network', 'Low Speed CAN Communication Bus'],
  ['U0020', 'network', 'Low Speed CAN Communication Bus Performance'],
  ['U0021', 'network', 'Low Speed CAN Communication Bus (+) Open'],
  ['U0022', 'network', 'Low Speed CAN Communication Bus (+) Low'],
  ['U0023', 'network', 'Low Speed CAN Communication Bus (+) High'],
  ['U0024', 'network', 'Low Speed CAN Communication Bus (-) Open'],
  ['U0025', 'network', 'Low Speed CAN Communication Bus (-) Low'],
  ['U0026', 'network', 'Low Speed CAN Communication Bus (-) High'],
  ['U0027', 'network', 'Low Speed CAN Communication Bus (-) Shorted to Bus (+)'],
  ['U0028', 'network', 'Vehicle Communication Bus A'],
  ['U0029', 'network', 'Vehicle Communication Bus A Performance'],
  ['U0030', 'network', 'Vehicle Communication Bus A (+) Open'],
  ['U0031', 'network', 'Vehicle Communication Bus A (+) Low'],
  ['U0032', 'network', 'Vehicle Communication Bus A (+) High'],
  ['U0033', 'network', 'Vehicle Communication Bus A (-) Open'],
  ['U0034', 'network', 'Vehicle Communication Bus A (-) Low'],
  ['U0035', 'network', 'Vehicle Communication Bus A (-) High'],
  ['U0036', 'network', 'Vehicle Communication Bus A (-) Shorted to Bus A (+)'],
  ['U0037', 'network', 'Vehicle Communication Bus B'],
  ['U0038', 'network', 'Vehicle Communication Bus B Performance'],
  ['U0039', 'network', 'Vehicle Communication Bus B (+) Open'],
  ['U0040', 'network', 'Vehicle Communication Bus B (+) Low'],
  ['U0041', 'network', 'Vehicle Communication Bus B (+) High'],
  ['U0042', 'network', 'Vehicle Communication Bus B (-) Open'],
  ['U0043', 'network', 'Vehicle Communication Bus B (-) Low'],
  ['U0044', 'network', 'Vehicle Communication Bus B (-) High'],
  ['U0045', 'network', 'Vehicle Communication Bus B (-) Shorted to Bus B (+)'],
  ['U0046', 'network', 'Vehicle Communication Bus C'],
  ['U0047', 'network', 'Vehicle Communication Bus C Performance'],
  ['U0048', 'network', 'Vehicle Communication Bus C (+) Open'],
  ['U0049', 'network', 'Vehicle Communication Bus C (+) Low'],
  ['U0050', 'network', 'Vehicle Communication Bus C (+) High'],
  ['U0051', 'network', 'Vehicle Communication Bus C (-) Open'],
  ['U0052', 'network', 'Vehicle Communication Bus C (-) Low'],
  ['U0053', 'network', 'Vehicle Communication Bus C (-) High'],
  ['U0054', 'network', 'Vehicle Communication Bus C (-) Shorted to Bus C (+)'],
  ['U0055', 'network', 'Vehicle Communication Bus D'],
  ['U0056', 'network', 'Vehicle Communication Bus D Performance'],
  ['U0057', 'network', 'Vehicle Communication Bus D (+) Open'],
  ['U0058', 'network', 'Vehicle Communication Bus D (+) Low'],
  ['U0059', 'network', 'Vehicle Communication Bus D (+) High'],
  ['U0060', 'network', 'Vehicle Communication Bus D (-) Open'],
  ['U0061', 'network', 'Vehicle Communication Bus D (-) Low'],
  ['U0062', 'network', 'Vehicle Communication Bus D (-) High'],
  ['U0063', 'network', 'Vehicle Communication Bus D (-) Shorted to Bus D (+)'],
  ['U0064', 'network', 'Vehicle Communication Bus E'],
  ['U0065', 'network', 'Vehicle Communication Bus E Performance'],
  ['U0066', 'network', 'Vehicle Communication Bus E (+) Open'],
  ['U0067', 'network', 'Vehicle Communication Bus E (+) Low'],
  ['U0068', 'network', 'Vehicle Communication Bus E (+) High'],
  ['U0069', 'network', 'Vehicle Communication Bus E (-) Open'],
  ['U0070', 'network', 'Vehicle Communication Bus E (-) Low'],
  ['U0071', 'network', 'Vehicle Communication Bus E (-) High'],
  ['U0072', 'network', 'Vehicle Communication Bus E (-) Shorted to Bus E (+)'],
  ['U0103', 'network', 'Lost Communication With Gear Shift Module'],
  ['U0104', 'network', 'Lost Communication With Cruise Control Module'],
  ['U0105', 'network', 'Lost Communication With Fuel Injector Control Module'],
  ['U0106', 'network', 'Lost Communication With Glow Plug Control Module'],
  ['U0107', 'network', 'Lost Communication With Throttle Actuator Control Module'],
  ['U0108', 'network', 'Lost Communication With Alternative Fuel Control Module'],
  ['U0109', 'network', 'Lost Communication With Fuel Pump Control Module'],
  ['U010A', 'network', 'Lost Communication With Exhaust Gas Recirculation Control Module A'],
  ['U010B', 'network', 'Lost Communication With Exhaust Gas Recirculation Control Module B'],
  ['U010C', 'network', 'Lost Communication With Turbocharger / Supercharger Control Module A'],
  ['U010D', 'network', 'Lost Communication With Turbocharger / Supercharger Control Module B'],
  ['U010E', 'network', 'Lost Communication With Reductant Control Module'],
  ['U010F', 'network', 'Lost Communication With Air Conditioning Control Module'],
  ['U0110', 'network', 'Lost Communication With Drive Motor Control Module'],
  ['U0111', 'network', 'Lost Communication With Battery Energy Control Module A'],
  ['U0112', 'network', 'Lost Communication With Battery Energy Control Module B'],
  ['U0113', 'network', 'Lost Communication With Emissions Critical Control Information'],
  ['U0114', 'network', 'Lost Communication With Four-Wheel Drive Clutch Control Module'],
  ['U0115', 'network', 'Lost Communication With ECM/PCM B'],
  ['U0288', 'network', 'Lost Communication With DC to DC Converter Control Module A'],
  ['U0289', 'network', 'Lost Communication With DC to DC Converter Control Module B'],
  ['U0290', 'network', 'Lost Communication With Shift Control Module A'],
  ['U0291', 'network', 'Lost Communication With Gear Shift Control Module B'],
  ['U0292', 'network', 'Lost Communication With Drive Motor Control Module B'],
  ['U0293', 'network', 'Lost Communication With Hybrid Powertrain Control Module'],
  ['U0294', 'network', 'Lost Communication With Powertrain Control Monitor Module'],
  ['U0295', 'network', 'Lost Communication With AC to AC Converter Control Module'],
  ['U0296', 'network', 'Lost Communication With AC to DC Converter Control Module A'],
  ['U0297', 'network', 'Lost Communication With AC to DC Converter Control Module B'],
  ['U0298', 'network', 'Lost Communication With DC to DC Converter Control Module C'],
  ['U0299', 'network', 'Lost Communication With DC to AC Converter Control Module A'],
  ['U029A', 'network', 'Lost Communication With DC to DC Converter Control Module D'],
  ['U029B', 'network', 'Lost Communication With Drive Motor Control Module C'],
  ['U029C', 'network', 'Lost Communication With Drive Motor Control Module D'],
  ['U029D', 'network', 'Lost Communication With NOX Sensor A'],
  ['U029E', 'network', 'Lost Communication With NOX Sensor B'],
  ['U0300', 'network', 'Internal Control Module Software Incompatibility'],
  ['U0301', 'network', 'Software Incompatibility With ECM/PCM'],
  ['U0302', 'network', 'Software Incompatibility With Transmission Control Module'],
  ['U0303', 'network', 'Software Incompatibility With Transfer Case Control Module'],
  ['U0304', 'network', 'Software Incompatibility With Gear Shift Control Module'],
  ['U0305', 'network', 'Software Incompatibility With Cruise Control Module'],
  ['U0306', 'network', 'Software Incompatibility With Fuel Injector Control Module'],
  ['U0307', 'network', 'Software Incompatibility With Glow Plug Control Module'],
  ['U0308', 'network', 'Software Incompatibility With Throttle Actuator Control Module'],
  ['U0309', 'network', 'Software Incompatibility With Alternative Fuel Control Module'],
  ['U0310', 'network', 'Software Incompatibility With Fuel Pump Control Module'],
  ['U0311', 'network', 'Software Incompatibility With Drive Motor Control Module'],
  ['U0312', 'network', 'Software Incompatibility With Battery Energy Control Module A'],
  ['U0313', 'network', 'Software Incompatibility With Battery Energy Control Module B'],
  ['U0314', 'network', 'Software Incompatibility With Four-Wheel Drive Clutch Control Module'],
  ['U0315', 'network', 'Software Incompatibility With Anti-Lock Brake System Control Module'],
  ['U0316', 'network', 'Software Incompatibility With Vehicle Dynamics Control Module'],
  ['U0317', 'network', 'Software Incompatibility With Park Brake Control Module'],
  ['U0318', 'network', 'Software Incompatibility With Brake System Control Module'],
  ['U0319', 'network', 'Software Incompatibility With Steering Effort Control Module'],
  ['U0320', 'network', 'Software Incompatibility With Power Steering Control Module'],
  ['U0321', 'network', 'Software Incompatibility With Ride Level Control Module'],
  ['U0322', 'network', 'Software Incompatibility With Body Control Module'],
  ['U0323', 'network', 'Software Incompatibility With Instrument Panel Control Module'],
  ['U0324', 'network', 'Software Incompatibility With HVAC Control Module'],
  ['U0325', 'network', 'Software Incompatibility With Auxiliary Heater Control Module'],
  ['U0326', 'network', 'Software Incompatibility With Immobilizer Control Module'],
  ['U0327', 'network', 'Software Incompatibility With Vehicle Security Control Module'],
  ['U0328', 'network', 'Software Incompatibility With Steering Angle Sensor Module'],
  ['U0329', 'network', 'Software Incompatibility With Steering Column Control Module'],
  ['U0330', 'network', 'Software Incompatibility With Tire Pressure Monitor Module'],
  ['U0331', 'network', 'Software Incompatibility With Body Control Module A'],
  ['U0400', 'network', 'Invalid Data Received'],
  ['U0401', 'network', 'Invalid Data Received From ECM/PCM A'],
  ['U0402', 'network', 'Invalid Data Received From Transmission Control Module'],
  ['U0403', 'network', 'Invalid Data Received From Transfer Case Control Module'],
  ['U0404', 'network', 'Invalid Data Received From Gear Shift Control Module'],
  ['U0405', 'network', 'Invalid Data Received From Cruise Control Module'],
  ['U0406', 'network', 'Invalid Data Received From Fuel Injector Control Module'],
  ['U0407', 'network', 'Invalid Data Received From Glow Plug Control Module'],
  ['U0408', 'network', 'Invalid Data Received From Throttle Actuator Control Module'],
  ['U0409', 'network', 'Invalid Data Received From Alternative Fuel Control Module'],
  ['U0410', 'network', 'Invalid Data Received From Fuel Pump Control Module'],
  ['U0411', 'network', 'Invalid Data Received From Drive Motor Control Module'],
  ['U0412', 'network', 'Invalid Data Received From Battery Energy Control Module A'],
  ['U0413', 'network', 'Invalid Data Received From Battery Energy Control Module B'],
  ['U0414', 'network', 'Invalid Data Received From Four-Wheel Drive Clutch Control Module'],
  ['U0415', 'network', 'Invalid Data Received From Anti-Lock Brake System Control Module'],
  ['U0416', 'network', 'Invalid Data Received From Vehicle Dynamics Control Module'],
  ['U0417', 'network', 'Invalid Data Received From Park Brake Control Module'],
  ['U0418', 'network', 'Invalid Data Received From Brake System Control Module'],
  ['U0419', 'network', 'Invalid Data Received From Steering Effort Control Module'],
  ['U0420', 'network', 'Invalid Data Received From Power Steering Control Module'],
  ['U0421', 'network', 'Invalid Data Received From Ride Level Control Module'],
  ['U0422', 'network', 'Invalid Data Received From Body Control Module'],
  ['U0423', 'network', 'Invalid Data Received From Instrument Panel Control Module'],
  ['U0424', 'network', 'Invalid Data Received From HVAC Control Module'],
];

function titleLocales(code, title) {
  return {
    en: title,
    tr: `${code} ${title} arızası`,
    de: `${title} Fehler`,
    es: `Falla de ${title}`,
    fr: `Défaut ${title}`,
  };
}

function descriptionLocales(code, title, system) {
  const profile = systemProfiles[system];
  return {
    en: `${code} indicates a fault related to ${title}. This is handled as a ${profile.label} diagnostic code. Confirm it with a scan tool that can access the correct module, check related codes, inspect power, ground, wiring and connectors, and verify the repair before replacing expensive modules or safety components.`,
    tr: `${code}, ${title} ile ilişkili bir arızayı gösterir. Bu kod ${profile.label} sistemi içinde değerlendirilmelidir. Doğru modüle erişebilen bir teşhis cihazıyla doğrulayın, ilişkili kodları okuyun, güç, şase, kablo ve soketleri kontrol edin; pahalı modül veya güvenlik parçası değiştirmeden önce onarımı doğrulayın.`,
    de: `${code} weist auf einen Fehler im Zusammenhang mit ${title} hin. Dieser Code gehört zum Bereich ${profile.label}. Mit einem Diagnosegerät für das passende Modul bestätigen, verwandte Codes prüfen, Stromversorgung, Masse, Kabel und Stecker kontrollieren und die Reparatur verifizieren.`,
    es: `${code} indica una falla relacionada con ${title}. Este código pertenece al sistema ${profile.label}. Confírmalo con un escáner que acceda al módulo correcto, revisa códigos relacionados, alimentación, masa, cableado y conectores antes de cambiar módulos o componentes de seguridad.`,
    fr: `${code} indique un défaut lié à ${title}. Ce code concerne le système ${profile.label}. Confirmez-le avec un outil capable d'accéder au bon module, vérifiez les codes associés, l'alimentation, la masse, le câblage et les connecteurs avant de remplacer des modules ou éléments de sécurité.`,
  };
}

for (const locale of Object.keys(symptomTokens)) {
  const file = path.join(messagesDir, `${locale}.json`);
  const data = JSON.parse(fs.readFileSync(file, 'utf8'));
  data.DB = { ...data.DB, ...symptomTokens[locale] };
  fs.writeFileSync(file, `${JSON.stringify(data, null, 2)}\n`);
}

const baseCodes = JSON.parse(fs.readFileSync(basePath, 'utf8'));
let added = 0;
let updated = 0;

for (const [code, system, title] of verifiedRows) {
  const profile = systemProfiles[system];
  const existed = Boolean(baseCodes[code]);
  baseCodes[code] = {
    ...baseCodes[code],
    title: titleLocales(code, title),
    description: descriptionLocales(code, title, system),
    symptoms: profile.symptoms,
    causes: profile.causes,
    fixDifficulty: profile.difficulty,
    estimatedCost: profile.cost,
    verifiedSource: profile.source,
  };
  if (existed) updated += 1;
  else added += 1;
}

const ordered = Object.fromEntries(Object.entries(baseCodes).sort(([a], [b]) => a.localeCompare(b)));
fs.writeFileSync(basePath, `${JSON.stringify(ordered, null, 2)}\n`);

const validRoutes = JSON.parse(fs.readFileSync(routesPath, 'utf8'));
validRoutes.validCodes = Object.keys(ordered).map(code => code.toUpperCase());
fs.writeFileSync(routesPath, `${JSON.stringify(validRoutes, null, 2)}\n`);

console.log(`Added ${added}, updated ${updated}. Total codes: ${validRoutes.validCodes.length}`);
