const fs = require('fs');
const path = require('path');
const {
  ROOT,
  LOCALES,
  loadJson,
  getRawGoldCodeSet,
  getGscSignalCodeSet,
  getValidCodeSet,
  isCodeHubSitemapEligible,
  codeHubPath,
} = require('./recovery_policy_helpers');

const rawGoldSet = getRawGoldCodeSet();
const gscSignalSet = getGscSignalCodeSet();
const validCodeSet = getValidCodeSet();

const failures = [];

for (const code of validCodeSet) {
  const eligible = isCodeHubSitemapEligible(code, rawGoldSet, gscSignalSet);
  if (!eligible && (rawGoldSet.has(code) || gscSignalSet.has(code))) {
    failures.push(`Policy contradiction for ${code}.`);
  }
}

const sitemapRoute = fs.readFileSync(path.join(ROOT, 'src/app/sitemaps/[id]/route.ts'), 'utf8');
if (!sitemapRoute.includes('isCodeHubSitemapEligible(code)')) {
  failures.push('Sitemap route does not apply code hub eligibility policy.');
}

const forbiddenUtilityPaths = [
  '/about',
  '/contact',
  '/editorial-policy',
  '/reviewers',
  '/privacy',
  '/terms',
  '/disclaimer',
];

for (const utilityPath of forbiddenUtilityPaths) {
  if (sitemapRoute.includes('`${BASE_URL}/${locale}' + utilityPath + '`')) {
    failures.push(`Utility/non-ranking URL still hard-coded in sitemap: ${utilityPath}`);
  }
}

const newsFiles = fs.readdirSync(path.join(ROOT, 'src/data/news')).filter((file) => file.endsWith('.json'));
const activeSlugs = new Set(newsFiles.map((file) => path.basename(file, '.json')));
const historicalAudit = path.join(ROOT, 'reports/seo/FINAL_REMOVED_NEWS_URL_AUDIT.csv');
if (fs.existsSync(historicalAudit)) {
  const removedRows = fs.readFileSync(historicalAudit, 'utf8').split(/\r?\n/).slice(1).filter(Boolean);
  for (const row of removedRows.slice(0, 200)) {
    const slug = row.split(',')[0];
    if (activeSlugs.has(slug)) continue;
    for (const locale of LOCALES) {
      const removedUrl = `/${locale}/news/${slug}`;
      if (sitemapRoute.includes(removedUrl)) failures.push(`Removed news URL found in sitemap source: ${removedUrl}`);
    }
  }
}

const sampleIneligible = [...validCodeSet].filter((code) => !isCodeHubSitemapEligible(code, rawGoldSet, gscSignalSet)).slice(0, 20);
if (sampleIneligible.length === 0) {
  failures.push('No ineligible fallback DTC sample found; policy may not be separating fallback URLs.');
}

const generatedEligibleCodeUrls = [];
for (const code of validCodeSet) {
  if (!isCodeHubSitemapEligible(code, rawGoldSet, gscSignalSet)) continue;
  for (const locale of LOCALES) generatedEligibleCodeUrls.push(codeHubPath(locale, code));
}

if (!generatedEligibleCodeUrls.length) {
  failures.push('No eligible code hub URLs generated by policy.');
}

const brandWarningBases = {
  en: 'warning-lights',
  tr: 'uyari-isiklari',
  de: 'warnleuchten',
  es: 'luces-tablero',
  fr: 'voyants-tableau-bord',
};

const opportunityRows = loadJson('src/data/generated/gsc-opportunities.json');
const gscWarningMakes = Array.from(new Set(
  opportunityRows
    .filter((row) => row.intentType === 'warning_light_make')
    .map((row) => String(row.targetUrl || '').split('/')[2])
    .filter(Boolean)
));

const sitemapBuckets = {
  'code-hubs': generatedEligibleCodeUrls,
  'gsc-opportunities': gscWarningMakes.flatMap((make) => (
    LOCALES.map((locale) => `/${locale}/${make}/${brandWarningBases[locale]}`)
  )),
};

const urlOwners = new Map();
for (const [bucket, urls] of Object.entries(sitemapBuckets)) {
  for (const url of urls) {
    const owners = urlOwners.get(url) || [];
    owners.push(bucket);
    urlOwners.set(url, owners);
  }
}

const duplicateSitemapUrls = [...urlOwners.entries()].filter(([, owners]) => owners.length > 1);
if (duplicateSitemapUrls.length) {
  failures.push(`Duplicate sitemap URL ownership found: ${duplicateSitemapUrls.slice(0, 5).map(([url, owners]) => `${url} (${owners.join(' + ')})`).join('; ')}`);
}

if (/getOpportunityCodes|gscCodes/.test(sitemapRoute)) {
  failures.push('GSC opportunities sitemap still emits code hub URLs; this recreates duplicate code-hub sitemap entries.');
}

if (failures.length) {
  console.error('Sitemap quality check failed:');
  for (const failure of failures) console.error(`- ${failure}`);
  process.exit(1);
}

console.log('Sitemap quality policy check passed.');
console.log(`Verified raw Gold code hubs: ${rawGoldSet.size}`);
console.log(`Fallback code hubs with GSC signal: ${[...gscSignalSet].filter((code) => !rawGoldSet.has(code)).length}`);
console.log(`Fallback code hubs removed from sitemap eligibility: ${sampleIneligible.length}+ sample confirmed`);
